// src/pages/home/index.tsx
import { Breadcrumb, Dropdown, Layout, Menu } from 'antd'
import { useEffect } from 'react'
import { Link, Outlet, useNavigate } from 'react-router-dom'
import { AdmMenu, DropDownMenu } from '../../constants'
import { useBreadRouterStore } from '../../store/useBreadRouterStore'
import { UserInfo } from './components/UserInfo'
import styles from './index.module.scss'

const { Header, Content, Footer } = Layout

export const HomePage = () => {
	const navigator = useNavigate()
	const BreadcrumbItems = useBreadRouterStore((state) => state.routers)
	const pushrouter = useBreadRouterStore((state) => state.pushrouter)
	const clearrouters = useBreadRouterStore((state) => state.clearrouters)
	useEffect(() => {
		// * 挂载时添加默认路由
		pushrouter({ title: '首页', path: '/' })
		return () => {
			clearrouters()
		}
	}, [])

	return (
		<>
			<Layout className={styles['Layout']}>
				<Header className={styles['Header']}>
					<div className={styles['HeaderContent']}>
						<h1 className={styles['HeaderTitle']}>CloudExam</h1>
						<Menu
							theme='light'
							mode='horizontal'
							items={AdmMenu}
							defaultActiveFirst={true}
							className={styles['HeaderMenu']}
							style={{ height: '72px' }}
							onClick={(e) => {
								clearrouters()
								pushrouter({
									title: (e.domEvent.target as HTMLElement).innerText as string,
									path: e.key,
								})
								navigator(e.key)
							}}
						/>
						<Dropdown
							menu={{ items: DropDownMenu }}
							placement='bottom'
							arrow={{ pointAtCenter: true }}
							className={styles['userInfoContainer']}
						>
							<UserInfo />
						</Dropdown>
					</div>
				</Header>

				<Content className={styles['Content']}>
					<div className={styles['bread']}>
						<Breadcrumb
							items={BreadcrumbItems}
							itemRender={(route, _params, routes, _paths) => {
								console.table(BreadcrumbItems)
								if (route.path === routes[0].path) {
									return (
										<Link
											to={route.path as string}
											onClick={() => {
												clearrouters()
												pushrouter({
													title: route.title as string,
													path: route.path as string,
												})
											}}
										>
											{route.title}
										</Link>
									)
								} else if (route.path === routes[routes.length - 1].path) {
									return <span>{route.title}</span>
								}
								return <Link to={route.path as string}>{route.title}</Link>
							}}
							// separator='>'
						></Breadcrumb>
					</div>
					<div className={styles['ContentContainer']}>
						<Outlet />
					</div>
				</Content>
				<Footer className={styles['Footer']}></Footer>
			</Layout>
		</>
	)
}

// src/pages/home/index.vue
<template>
  <div>
    <el-container class="'Layout'">
      <el-header class="Header">
        <div class="HeaderContent">
          <h1 class="HeaderTitle">CloudExam</h1>
          <el-menu
            theme="light"
            mode="horizontal"
            class="HeaderMenu"
            :style="{ height: '72px' }"
          >
            <template v-for="item in AdmMenu" :key="item.key">
              <el-menu-item
                :index="item.key"
                @click="
                  (e) => {
                    breadRouterStore.clearRouter();
                    breadRouterStore.pushRouter({
                      title: (e.target as HTMLElement).innerText,
                      path: e.key,
                    });
                    router.push(e.key);
                  }
                "
              >
                <template #title>
                  {{ item.label }}
                </template>
              </el-menu-item>
            </template>
          </el-menu>
          <el-dropdown placement="bottom">
            <userInfo />
            <arrow-down />
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item v-for="item in DropDownMenu">
                  {{ item.label }}
                </el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </div>
      </el-header>
      <el-content class="Content">
        <div class="bread">
          <el-breadcrumb separator=">">
            <el-breadcrumb-item
              v-for="(item, index) in breadRouterStore.router"
              :key="index"
              :to="{ path: item.path }"
              @click="
                () => {
                  breadRouterStore.clearRouter();
                  breadRouterStore.pushRouter({
                    title: item.title,
                    path: item.path,
                  });
                }
              "
            >
              {{ item.title }}
            </el-breadcrumb-item>
          </el-breadcrumb>
        </div>
        <div class="ContentContainer">
          <router-view />
        </div>
      </el-content>
      <el-footer class="Footer"></el-footer>
    </el-container>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from "vue";
import { useBreadRouterStore } from "@/store/useBreadRouterStore";
import { useRouter } from "vue-router";
import { AdmMenu, DropDownMenu } from "src/constants";
import userInfo from "./components/UserInfo/userInfo.vue";
import { ArrowDown } from "@element-plus/icons-vue";
const breadRouterStore = useBreadRouterStore();
const router = useRouter();
onMounted(() => {});
</script>

<style lang="scss" scoped></style>
