// src/pages/home/components/UserInfo/index.tsx
import { ComponentProps } from 'react'
import { ArrowDown } from '../../../../assets/icons'
import styles from './index.module.scss'
export const UserInfo = ({
	className,
	...props
}: {
	className?: string
	props?: ComponentProps<'div'>
}) => {
	return (
		<div className={[styles['userInfo'], className].join(' ')} {...props}>
			<span className={styles['headerName']}>刘旭峰</span>
			<span>
				<span className={styles['schoolName']}>幸福中学(高中)</span>
				<ArrowDown />
			</span>
		</div>
	)
}

// src/pages/home/components/UserInfo/userInfo.vue
<template>
    <div class="userInfo" :class="className" v-bind="props">
        <span class="headerName">刘旭峰</span>
        <span>
            <span class="schoolName">中南大学</span>
            <arrowDown />
        </span>
    </div>
</template>

<script setup lang="ts">
import{UserInfoType} from './type'
//@ts-ignore
import {arrowDown} from '@/assets/arrowDown.vue'
const {className, props} = defineProps<UserInfoType>()

</script>

<style scoped src="'./index.module.scss'">

</style>
